/**
 * This is an example similar to what we get from Leetcode API upon sending valid LEETCODE_SESSION cookie
 */

export default {
	user_name: "NEO-The-Chosen-One",
	num_solved: 388,
	num_total: 1812,
	ac_easy: 85,
	ac_medium: 213,
	ac_hard: 90,
	stat_status_pairs: [
		{
			stat: {
				question_id: 2141,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Smallest Greater Multiple Made of Two Digits",
				question__title_slug:
					"smallest-greater-multiple-made-of-two-digits",
				question__hide: false,
				total_acs: 329,
				total_submitted: 574,
				frontend_question_id: 1999,
				is_new_question: true,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2131,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Smallest Missing Genetic Value in Each Subtree",
				question__title_slug:
					"smallest-missing-genetic-value-in-each-subtree",
				question__hide: false,
				total_acs: 2356,
				total_submitted: 6221,
				frontend_question_id: 2003,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2130,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Maximum Product of the Length of Two Palindromic Subsequences",
				question__title_slug:
					"maximum-product-of-the-length-of-two-palindromic-subsequences",
				question__hide: false,
				total_acs: 5993,
				total_submitted: 12407,
				frontend_question_id: 2002,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2129,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Number of Pairs of Interchangeable Rectangles",
				question__title_slug:
					"number-of-pairs-of-interchangeable-rectangles",
				question__hide: false,
				total_acs: 9300,
				total_submitted: 23189,
				frontend_question_id: 2001,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2128,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Reverse Prefix of Word",
				question__title_slug: "reverse-prefix-of-word",
				question__hide: false,
				total_acs: 10479,
				total_submitted: 13051,
				frontend_question_id: 2000,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2126,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Count Nodes Equal to Sum of Descendants",
				question__title_slug: "count-nodes-equal-to-sum-of-descendants",
				question__hide: false,
				total_acs: 1042,
				total_submitted: 1338,
				frontend_question_id: 1973,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2125,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "GCD Sort of an Array",
				question__title_slug: "gcd-sort-of-an-array",
				question__hide: false,
				total_acs: 3026,
				total_submitted: 6682,
				frontend_question_id: 1998,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2124,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"First Day Where You Have Been in All the Rooms",
				question__title_slug:
					"first-day-where-you-have-been-in-all-the-rooms",
				question__hide: false,
				total_acs: 3641,
				total_submitted: 10783,
				frontend_question_id: 1997,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2123,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "The Number of Weak Characters in the Game",
				question__title_slug:
					"the-number-of-weak-characters-in-the-game",
				question__hide: false,
				total_acs: 8418,
				total_submitted: 30712,
				frontend_question_id: 1996,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2122,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Count Special Quadruplets",
				question__title_slug: "count-special-quadruplets",
				question__hide: false,
				total_acs: 10906,
				total_submitted: 19800,
				frontend_question_id: 1995,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2121,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Find if Path Exists in Graph",
				question__title_slug: "find-if-path-exists-in-graph",
				question__hide: false,
				total_acs: 12168,
				total_submitted: 23884,
				frontend_question_id: 1971,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2115,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Number of Unique Good Subsequences",
				question__title_slug: "number-of-unique-good-subsequences",
				question__hide: false,
				total_acs: 3194,
				total_submitted: 6479,
				frontend_question_id: 1987,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2114,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Minimum Number of Work Sessions to Finish the Tasks",
				question__title_slug:
					"minimum-number-of-work-sessions-to-finish-the-tasks",
				question__hide: false,
				total_acs: 7410,
				total_submitted: 24154,
				frontend_question_id: 1986,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2113,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Find the Kth Largest Integer in the Array",
				question__title_slug:
					"find-the-kth-largest-integer-in-the-array",
				question__hide: false,
				total_acs: 12585,
				total_submitted: 29225,
				frontend_question_id: 1985,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2112,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Minimum Difference Between Highest and Lowest of K Scores",
				question__title_slug:
					"minimum-difference-between-highest-and-lowest-of-k-scores",
				question__hide: false,
				total_acs: 12040,
				total_submitted: 22229,
				frontend_question_id: 1984,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2111,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Binary Searchable Numbers in an Unsorted Array",
				question__title_slug:
					"binary-searchable-numbers-in-an-unsorted-array",
				question__hide: false,
				total_acs: 608,
				total_submitted: 929,
				frontend_question_id: 1966,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2109,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Find Array Given Subset Sums",
				question__title_slug: "find-array-given-subset-sums",
				question__hide: false,
				total_acs: 1729,
				total_submitted: 3788,
				frontend_question_id: 1982,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2108,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Minimize the Difference Between Target and Chosen Elements",
				question__title_slug:
					"minimize-the-difference-between-target-and-chosen-elements",
				question__hide: false,
				total_acs: 10106,
				total_submitted: 31796,
				frontend_question_id: 1981,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2107,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Find Unique Binary String",
				question__title_slug: "find-unique-binary-string",
				question__hide: false,
				total_acs: 12972,
				total_submitted: 21181,
				frontend_question_id: 1980,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2106,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Find Greatest Common Divisor of Array",
				question__title_slug: "find-greatest-common-divisor-of-array",
				question__hide: false,
				total_acs: 17269,
				total_submitted: 21384,
				frontend_question_id: 1979,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2105,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "The Number of Good Subsets",
				question__title_slug: "the-number-of-good-subsets",
				question__hide: false,
				total_acs: 1937,
				total_submitted: 6356,
				frontend_question_id: 1994,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2104,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Operations on Tree",
				question__title_slug: "operations-on-tree",
				question__hide: false,
				total_acs: 3945,
				total_submitted: 9768,
				frontend_question_id: 1993,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2103,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Find All Groups of Farmland",
				question__title_slug: "find-all-groups-of-farmland",
				question__hide: false,
				total_acs: 6592,
				total_submitted: 10399,
				frontend_question_id: 1992,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2102,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Find the Middle Index in Array",
				question__title_slug: "find-the-middle-index-in-array",
				question__hide: false,
				total_acs: 9886,
				total_submitted: 15705,
				frontend_question_id: 1991,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2101,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Last Day Where You Can Still Cross",
				question__title_slug: "last-day-where-you-can-still-cross",
				question__hide: false,
				total_acs: 6032,
				total_submitted: 12901,
				frontend_question_id: 1970,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2100,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Minimum Non-Zero Product of the Array Elements",
				question__title_slug:
					"minimum-non-zero-product-of-the-array-elements",
				question__hide: false,
				total_acs: 5433,
				total_submitted: 17316,
				frontend_question_id: 1969,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2099,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Number of Strings That Appear as Substrings in Word",
				question__title_slug:
					"number-of-strings-that-appear-as-substrings-in-word",
				question__hide: false,
				total_acs: 15225,
				total_submitted: 19653,
				frontend_question_id: 1967,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2096,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Find the Longest Valid Obstacle Course at Each Position",
				question__title_slug:
					"find-the-longest-valid-obstacle-course-at-each-position",
				question__hide: false,
				total_acs: 6467,
				total_submitted: 14998,
				frontend_question_id: 1964,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2095,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Minimum Number of Swaps to Make the String Balanced",
				question__title_slug:
					"minimum-number-of-swaps-to-make-the-string-balanced",
				question__hide: false,
				total_acs: 12382,
				total_submitted: 19414,
				frontend_question_id: 1963,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2094,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Remove Stones to Minimize the Total",
				question__title_slug: "remove-stones-to-minimize-the-total",
				question__hide: false,
				total_acs: 12837,
				total_submitted: 24123,
				frontend_question_id: 1962,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2093,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Check If String Is a Prefix of Array",
				question__title_slug: "check-if-string-is-a-prefix-of-array",
				question__hide: false,
				total_acs: 16340,
				total_submitted: 30122,
				frontend_question_id: 1961,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2091,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Number of Ways to Separate Numbers",
				question__title_slug: "number-of-ways-to-separate-numbers",
				question__hide: false,
				total_acs: 1492,
				total_submitted: 6393,
				frontend_question_id: 1977,
				is_new_question: false,
			},
			status: "notac",
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2090,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Number of Ways to Arrive at Destination",
				question__title_slug: "number-of-ways-to-arrive-at-destination",
				question__hide: false,
				total_acs: 5888,
				total_submitted: 19095,
				frontend_question_id: 1976,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2089,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Maximum Matrix Sum",
				question__title_slug: "maximum-matrix-sum",
				question__hide: false,
				total_acs: 6887,
				total_submitted: 16068,
				frontend_question_id: 1975,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2088,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Minimum Time to Type Word Using Special Typewriter",
				question__title_slug:
					"minimum-time-to-type-word-using-special-typewriter",
				question__hide: false,
				total_acs: 10380,
				total_submitted: 14232,
				frontend_question_id: 1974,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2086,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Count Number of Special Subsequences",
				question__title_slug: "count-number-of-special-subsequences",
				question__hide: false,
				total_acs: 5800,
				total_submitted: 11682,
				frontend_question_id: 1955,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2085,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Array With Elements Not Equal to Average of Neighbors",
				question__title_slug:
					"array-with-elements-not-equal-to-average-of-neighbors",
				question__hide: false,
				total_acs: 12225,
				total_submitted: 26227,
				frontend_question_id: 1968,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2084,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Maximum Number of Weeks for Which You Can Work",
				question__title_slug:
					"maximum-number-of-weeks-for-which-you-can-work",
				question__hide: false,
				total_acs: 9821,
				total_submitted: 28348,
				frontend_question_id: 1953,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2083,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Three Divisors",
				question__title_slug: "three-divisors",
				question__hide: false,
				total_acs: 17648,
				total_submitted: 31552,
				frontend_question_id: 1952,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2081,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Minimum Total Space Wasted With K Resizing Operations",
				question__title_slug:
					"minimum-total-space-wasted-with-k-resizing-operations",
				question__hide: false,
				total_acs: 3577,
				total_submitted: 8894,
				frontend_question_id: 1959,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2080,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Check if Move is Legal",
				question__title_slug: "check-if-move-is-legal",
				question__hide: false,
				total_acs: 5663,
				total_submitted: 13605,
				frontend_question_id: 1958,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2079,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Delete Duplicate Folders in System",
				question__title_slug: "delete-duplicate-folders-in-system",
				question__hide: false,
				total_acs: 2833,
				total_submitted: 4687,
				frontend_question_id: 1948,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2078,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Maximum Compatibility Score Sum",
				question__title_slug: "maximum-compatibility-score-sum",
				question__hide: false,
				total_acs: 10141,
				total_submitted: 17596,
				frontend_question_id: 1947,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2077,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Largest Number After Mutating Substring",
				question__title_slug: "largest-number-after-mutating-substring",
				question__hide: false,
				total_acs: 12029,
				total_submitted: 36388,
				frontend_question_id: 1946,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2076,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Sum of Digits of String After Convert",
				question__title_slug: "sum-of-digits-of-string-after-convert",
				question__hide: false,
				total_acs: 16249,
				total_submitted: 26205,
				frontend_question_id: 1945,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2074,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Erect the Fence II",
				question__title_slug: "erect-the-fence-ii",
				question__hide: false,
				total_acs: 354,
				total_submitted: 556,
				frontend_question_id: 1924,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2073,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Minimum Time For K Virus Variants to Spread",
				question__title_slug:
					"minimum-time-for-k-virus-variants-to-spread",
				question__hide: false,
				total_acs: 261,
				total_submitted: 570,
				frontend_question_id: 1956,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2072,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Maximum of Minimum Values in All Subarrays",
				question__title_slug:
					"maximum-of-minimum-values-in-all-subarrays",
				question__hide: false,
				total_acs: 447,
				total_submitted: 879,
				frontend_question_id: 1950,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2071,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Longest Common Subsequence Between Sorted Arrays",
				question__title_slug:
					"longest-common-subsequence-between-sorted-arrays",
				question__hide: false,
				total_acs: 1591,
				total_submitted: 1961,
				frontend_question_id: 1940,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2070,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Check if String Is Decomposable Into Value-Equal Substrings",
				question__title_slug:
					"check-if-string-is-decomposable-into-value-equal-substrings",
				question__hide: false,
				total_acs: 1189,
				total_submitted: 2121,
				frontend_question_id: 1933,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2069,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Kth Smallest Subarray Sum",
				question__title_slug: "kth-smallest-subarray-sum",
				question__hide: false,
				total_acs: 933,
				total_submitted: 1711,
				frontend_question_id: 1918,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2068,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Maximum Genetic Difference Query",
				question__title_slug: "maximum-genetic-difference-query",
				question__hide: false,
				total_acs: 2512,
				total_submitted: 6637,
				frontend_question_id: 1938,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2067,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Maximum Number of Points with Cost",
				question__title_slug: "maximum-number-of-points-with-cost",
				question__hide: false,
				total_acs: 9268,
				total_submitted: 32359,
				frontend_question_id: 1937,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2066,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Add Minimum Number of Rungs",
				question__title_slug: "add-minimum-number-of-rungs",
				question__hide: false,
				total_acs: 14926,
				total_submitted: 36027,
				frontend_question_id: 1936,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2062,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Game of Nim",
				question__title_slug: "game-of-nim",
				question__hide: false,
				total_acs: 492,
				total_submitted: 791,
				frontend_question_id: 1908,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2061,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Painting a Grid With Three Different Colors",
				question__title_slug:
					"painting-a-grid-with-three-different-colors",
				question__hide: false,
				total_acs: 4516,
				total_submitted: 8079,
				frontend_question_id: 1931,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2060,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Merge BSTs to Create Single BST",
				question__title_slug: "merge-bsts-to-create-single-bst",
				question__hide: false,
				total_acs: 2790,
				total_submitted: 8452,
				frontend_question_id: 1932,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2059,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Unique Length-3 Palindromic Subsequences",
				question__title_slug:
					"unique-length-3-palindromic-subsequences",
				question__hide: false,
				total_acs: 12775,
				total_submitted: 25825,
				frontend_question_id: 1930,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2058,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Concatenation of Array",
				question__title_slug: "concatenation-of-array",
				question__hide: false,
				total_acs: 55173,
				total_submitted: 59613,
				frontend_question_id: 1929,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2055,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Describe the Painting",
				question__title_slug: "describe-the-painting",
				question__hide: false,
				total_acs: 5564,
				total_submitted: 12378,
				frontend_question_id: 1943,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2054,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "The Number of the Smallest Unoccupied Chair",
				question__title_slug:
					"the-number-of-the-smallest-unoccupied-chair",
				question__hide: false,
				total_acs: 8460,
				total_submitted: 22962,
				frontend_question_id: 1942,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2053,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"Check if All Characters Have Equal Number of Occurrences",
				question__title_slug:
					"check-if-all-characters-have-equal-number-of-occurrences",
				question__hide: false,
				total_acs: 17903,
				total_submitted: 23242,
				frontend_question_id: 1941,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2052,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Depth of BST Given Insertion Order",
				question__title_slug: "depth-of-bst-given-insertion-order",
				question__hide: false,
				total_acs: 824,
				total_submitted: 1660,
				frontend_question_id: 1902,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2051,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Longest Common Subpath",
				question__title_slug: "longest-common-subpath",
				question__hide: false,
				total_acs: 3291,
				total_submitted: 12064,
				frontend_question_id: 1923,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2050,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Count Good Numbers",
				question__title_slug: "count-good-numbers",
				question__hide: false,
				total_acs: 11000,
				total_submitted: 28543,
				frontend_question_id: 1922,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2049,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Eliminate Maximum Number of Monsters",
				question__title_slug: "eliminate-maximum-number-of-monsters",
				question__hide: false,
				total_acs: 12818,
				total_submitted: 34193,
				frontend_question_id: 1921,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2048,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Build Array from Permutation",
				question__title_slug: "build-array-from-permutation",
				question__hide: false,
				total_acs: 50990,
				total_submitted: 54972,
				frontend_question_id: 1920,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2047,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Find a Peak Element II",
				question__title_slug: "find-a-peak-element-ii",
				question__hide: false,
				total_acs: 5802,
				total_submitted: 9817,
				frontend_question_id: 1901,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2045,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Cutting Ribbons",
				question__title_slug: "cutting-ribbons",
				question__hide: false,
				total_acs: 4797,
				total_submitted: 9289,
				frontend_question_id: 1891,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2044,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Number of Wonderful Substrings",
				question__title_slug: "number-of-wonderful-substrings",
				question__hide: false,
				total_acs: 5575,
				total_submitted: 14071,
				frontend_question_id: 1915,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2043,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Cyclically Rotating a Grid",
				question__title_slug: "cyclically-rotating-a-grid",
				question__hide: false,
				total_acs: 7205,
				total_submitted: 16373,
				frontend_question_id: 1914,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2042,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Maximum Product Difference Between Two Pairs",
				question__title_slug:
					"maximum-product-difference-between-two-pairs",
				question__hide: false,
				total_acs: 28852,
				total_submitted: 35340,
				frontend_question_id: 1913,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2040,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Minimum Cost to Reach Destination in Time",
				question__title_slug:
					"minimum-cost-to-reach-destination-in-time",
				question__hide: false,
				total_acs: 5474,
				total_submitted: 15612,
				frontend_question_id: 1928,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2039,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Sum Game",
				question__title_slug: "sum-game",
				question__hide: false,
				total_acs: 4938,
				total_submitted: 10489,
				frontend_question_id: 1927,
				is_new_question: false,
			},
			status: "notac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2038,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Nearest Exit from Entrance in Maze",
				question__title_slug: "nearest-exit-from-entrance-in-maze",
				question__hide: false,
				total_acs: 9386,
				total_submitted: 25888,
				frontend_question_id: 1926,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2037,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Count Square Sum Triples",
				question__title_slug: "count-square-sum-triples",
				question__hide: false,
				total_acs: 13822,
				total_submitted: 21052,
				frontend_question_id: 1925,
				is_new_question: false,
			},
			status: "ac",
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2036,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Count Pairs in Two Arrays",
				question__title_slug: "count-pairs-in-two-arrays",
				question__hide: false,
				total_acs: 1129,
				total_submitted: 1996,
				frontend_question_id: 1885,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2035,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Count Sub Islands",
				question__title_slug: "count-sub-islands",
				question__hide: false,
				total_acs: 13514,
				total_submitted: 22144,
				frontend_question_id: 1905,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2034,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Minimum Absolute Difference Queries",
				question__title_slug: "minimum-absolute-difference-queries",
				question__hide: false,
				total_acs: 6085,
				total_submitted: 14408,
				frontend_question_id: 1906,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2033,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "The Number of Full Rounds You Have Played",
				question__title_slug:
					"the-number-of-full-rounds-you-have-played",
				question__hide: false,
				total_acs: 14033,
				total_submitted: 28819,
				frontend_question_id: 1904,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2032,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Largest Odd Number in String",
				question__title_slug: "largest-odd-number-in-string",
				question__hide: false,
				total_acs: 21562,
				total_submitted: 37465,
				frontend_question_id: 1903,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 1,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2031,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Egg Drop With 2 Eggs and N Floors",
				question__title_slug: "egg-drop-with-2-eggs-and-n-floors",
				question__hide: false,
				total_acs: 9209,
				total_submitted: 13176,
				frontend_question_id: 1884,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2029,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Minimize Product Sum of Two Arrays",
				question__title_slug: "minimize-product-sum-of-two-arrays",
				question__hide: false,
				total_acs: 3093,
				total_submitted: 3439,
				frontend_question_id: 1874,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: true,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2028,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title:
					"The Earliest and Latest Rounds Where Players Compete",
				question__title_slug:
					"the-earliest-and-latest-rounds-where-players-compete",
				question__hide: false,
				total_acs: 3228,
				total_submitted: 6428,
				frontend_question_id: 1900,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 3,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
		{
			stat: {
				question_id: 2027,
				question__article__live: null,
				question__article__slug: null,
				question__article__has_video_solution: null,
				question__title: "Maximum Number of Removable Characters",
				question__title_slug: "maximum-number-of-removable-characters",
				question__hide: false,
				total_acs: 9672,
				total_submitted: 28715,
				frontend_question_id: 1898,
				is_new_question: false,
			},
			status: null,
			difficulty: {
				level: 2,
			},
			paid_only: false,
			is_favor: false,
			frequency: 0,
			progress: 0,
		},
	],
	frequency_high: 0,
	frequency_mid: 0,
	category_slug: "algorithms",
};
